theme = "kanagawa"

[editor]
line-number = "relative"
cursor-shape = { insert = "bar", normal = "block", select = "underline" }
auto-save = true
auto-format = true
bufferline = "always"

[editor.file-picker]
hidden = false

[keys.normal]
"space" = { q = ":quit-all", s = ":write" }
