# import the theme and other live_config_reload
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

live_config_reload = true

[window]
padding = { x = 10, y = 10 }
startup_mode = "Fullscreen" # "Maximized"
decorations = "Buttonless" # "None" for the window borders
dynamic_title = false

[window.dimensions]
columns = 125
lines = 35

# to allow the colors for the theme
[env]
TERM = "xterm-256color"

[cursor]
style = { shape = "Underline", blinking = "Always"}

# by default it is using mono nerd
[font]
size = 15 

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" }
]

